Added ArtStation support
y-young/nazurin pull request #28
Opened 2021-11-04 00:45 UTC by dearrrfish

2021-11-04 15:41 UTC, y-young requested changes
Thanks for your contribution! The code looks good overall, but it can be better with some adjustments, please see the comments.

2021-11-04 15:41 UTC, y-young commented on nazurin/sites/Artstation/api.py
> +                if not response.text:
It would be better by checking if the response code is 404.

2021-11-04 15:41 UTC, y-young commented on nazurin/sites/Artstation/config.py
> +PRIORITY = 11
Let's set the priority the same as Pixiv, which is 10.

2021-11-04 15:41 UTC, y-young commented on nazurin/sites/Artstation/api.py
> +        thumbnail = baseurl.replace('/large/', '/small_square/')
Normally we want to keep the heigh-width ratio, so "medium" is a better option, e.g: https://cdnb.artstation.com/p/assets/covers/images/042/647/153/medium/_z-ed_-z-ed-da2.jpg

2021-11-04 15:41 UTC, y-young commented on nazurin/sites/Artstation/api.py
> +                'https://cdnb.artstation.com/p/assets/images/images/042/908/363/large/_z-ed_-da.jpg',
I noticed that "large" is not necessarily the image of the best quality we can get, and the size of "large" image doesn't match that in "assets", "4k" seems a better option, e.g: https://cdna.artstation.com/p/assets/images/images/042/647/078/4k/_z-ed_-da1.jpg?1635092391

2021-11-04 19:07 UTC, dearrrfish commented on nazurin/sites/Artstation/api.py
> +                if not response.text:
sure, fixed.

2021-11-04 19:08 UTC, dearrrfish commented on nazurin/sites/Artstation/api.py
> +                'https://cdnb.artstation.com/p/assets/images/images/042/908/363/large/_z-ed_-da.jpg',
Good to know! Thank you!

2021-11-05 06:22 UTC, y-young approved these changes

2021-11-05 06:22 UTC, merged

2021-11-05 06:23 UTC, y-young commented
Thank you!