Add OneDrive Storage Support
y-young/nazurin pull request #8
Opened 2021-01-30 13:47 UTC by weremexii

Use [msal](https://github.com/AzureAD/microsoft-authentication-library-for-python) and [microsoftgraph-python](https://github.com/GearPlug/microsoftgraph-python) to access OneDrive resources.

Because of the function realization limit of microsoftgraph-python, the code directly make requests by methods like `_post` provided by microsoftgraph-python. For further development the bot can directly use parts of its source code.

And if this PR can be accepted , I'm delighted to write a wiki for onedrive configuration.

---

Something unrelated to the PR:

这是我第一次交PR,有什么问题还请包涵

在给自己搭个bot的时候找到这个项目,觉得很厉害,因为自己有微软的E5订阅,于是想给项目写一下OneDrive的存储

自己是Python新手,代码风格是“沿袭”大大的

祝新年快乐

2021-01-30 13:53 UTC, weremexii commented
I need to correct something...

2021-01-30 14:02 UTC, y-young commented
你好~
前几天偶然看到你在写这个Feature，原本我也正计划着适配OneDrive，但是还没开工，所以提前感谢你的贡献
代码看起来还是不错的，如果有细节问题我们可以在PR中修正
如果PR测试没通过的话可以继续向你的分支commit来进行修改，不必着急
此外我近期正在进行v2版本的编写，之后API方面可能有些小改动，但你可以先写，后面由我来修改

2021-01-30 14:14 UTC, weremexii commented
感谢理解

我想先搬一下microsoftgraph-python的部分实现,毕竟就api而言它实现的功能和bot的需要是不对应的

另外保存在Firebase的token也许多不必要的信息,我想试着清理一下

PS: Open PR后的代码检查还会检查空行的吗...

2021-01-30 14:20 UTC, y-young commented
> 感谢理解
> 
> 我想先搬一下microsoftgraph-python的部分实现,毕竟就api而言它实现的功能和bot的需要是不对应的
> 
> 另外保存在Firebase的token也许多不必要的信息,我想试着清理一下
> 
> PS: Open PR后的代码检查还会检查空行的吗...

这个代码风格检查是为了保证代码风格的统一性，因为可能存在误判的情况，所以有些细节即使没有通过检查也没有关系，我看看没有问题就行
当然比较常规的地方还是注意一下比较好，比如逗号后加个空格：
```python
environ.get('OD_RF_TOKEN', None)
{"name": "Pictures", "folder": {}}
```

2021-01-30 14:26 UTC, weremexii commented
别骂了别骂了.jpg

我去全部检查一遍

话说PR reopen后就可以跟踪新的commit了吧

2021-01-30 14:27 UTC, y-young commented
> 别骂了别骂了.jpg
> 
> 我去全部检查一遍
> 
> 话说PR reopen后就可以跟踪新的commit了吧

应该是的，你可以试试(

2021-01-30 14:48 UTC, y-young requested changes

2021-01-30 14:48 UTC, y-young commented on storage/onedrive.py
> +
此处有多余的空格

2021-01-30 14:53 UTC, weremexii commented on storage/onedrive.py
> +
终于找到了QAQ

2021-01-30 14:55 UTC, y-young commented
好了，明天我会具体看一下代码然后测试一下功能

2021-01-30 14:56 UTC, y-young approved these changes

2021-01-31 05:05 UTC, y-young commented on storage/onedrive.py
> +        token = self.api.refresh_token(OD_RD_URL, refresh_token)
这个和下面的 `acquire_token_by_refresh_token`有何区别？`refresh_token`是不是需要事先手动获取？

2021-01-31 05:18 UTC, weremexii commented on storage/onedrive.py
> +        token = self.api.refresh_token(OD_RD_URL, refresh_token)
这个方法可以获取`access token`,也就是连接Graph资源要使用的

下面的`acquire_token_by_refresh_token `是用来更新`refresh_token`的

---

`refresh_token`是要事先获取的,填写在`OD_RF_TOKEN`里面

2021-01-31 05:20 UTC, weremexii commented on storage/onedrive.py
> +        token = self.api.refresh_token(OD_RD_URL, refresh_token)
今天我看了一下`refresh_token`这个方法,发现它也是可以更新refresh_token的

于是用它替代了`acquire_token_by_refresh_token`,也就是不需要msal库了

然后搬了一下microsoftgraph的部分代码

2021-01-31 05:31 UTC, y-young commented on storage/onedrive.py
> +        token = self.api.refresh_token(OD_RD_URL, refresh_token)
refresh_token为何需要更新？过期时间是多久？
如果用msal能否实现同样的效果？这样就不需要redirect_url了

2021-01-31 05:42 UTC, weremexii commented on storage/onedrive.py
> +        token = self.api.refresh_token(OD_RD_URL, refresh_token)
微软给的refresh_token过期时间是90天,我这边还不了解bot是否会定期更新auth信息,所以设置成了每次上传前更新

redirect_url还是需要的,注册在微软的App在向服务器请求token时必须附上注册时填写的redirect_url

redirect_url主要是和部署bot前手动获取refresh_token有关,在部署bot时它只是更新token的必要参数

2021-01-31 05:45 UTC, y-young commented on storage/onedrive.py
> +        token = self.api.refresh_token(OD_RD_URL, refresh_token)
> 微软给的refresh_token过期时间是90天,我这边还不了解bot是否会定期更新auth信息,所以设置成了每次上传前更新
> 
> redirect_url还是需要的,注册在微软的App在向服务器请求token时必须附上注册时填写的redirect_url
> 
> redirect_url主要是和部署bot前手动获取refresh_token有关,在部署bot时它只是更新token的必要参数

我刚才用了msal那个函数，发现并不需要redirect_url

2021-01-31 05:55 UTC, weremexii commented on storage/onedrive.py
> +        token = self.api.refresh_token(OD_RD_URL, refresh_token)
是我疏忽了，写的时候基本把它当必要参数用

2021-01-31 06:00 UTC, weremexii commented
刚才发现了一个很大的bug

文件是实现上传了，不过文件下载下来是无法打开的

可能是PUT的header里没有附带Content-Type

2021-01-31 06:03 UTC, y-young commented
> 刚才发现了一个很大的bug
> 
> 文件是实现上传了，不过文件下载下来是无法打开的
> 
> 可能是PUT的header里没有附带Content-Type

可以把代码相关的API文档链接写在这边以供参考
印象中refresh_token确实需要手动获取，这个暂时不要紧
redirect_url麻烦你再确定一下，如果可以的话还是去掉这个环境变量比较好

2021-01-31 06:09 UTC, weremexii commented
我回去测试一下

现在是打算保留msal吧

microsoftgraph我觉得还是去掉比较好

2021-01-31 06:22 UTC, y-young commented
> 我回去测试一下
> 
> 现在是打算保留msal吧
> 
> microsoftgraph我觉得还是去掉比较好

看看，如果msal用得不多而且实现简单的话也可以自己写，毕竟后面需要改成异步请求

2021-01-31 09:36 UTC, weremexii commented
Update

参考了microsoftgraph的代码实现了refresh_token的更新,redirect_url是可以去掉的

修好了文件上传的bug

添加了api的文档链接

2021-01-31 15:16 UTC, y-young requested changes

2021-01-31 15:16 UTC, y-young commented on storage/onedrive.py
> +        # https://docs.microsoft.com/zh-cn/graph/api/driveitem-createuploadsession?view=graph-rest-1.0
> 通过简单的上载 API，你可以在单个 API 调用中提供新文件的内容，也可以更新现有文件的内容。此方法仅支持最大大小为 4 MB 的文件。(https://docs.microsoft.com/zh-cn/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)

文件上传有点问题，由于API限制，超过4MB的文件需要分块上传，详见 https://docs.microsoft.com/zh-cn/graph/api/driveitem-createuploadsession?view=graph-rest-1.0
如果实现起来有点麻烦的话可以找找现成的库

2021-02-01 06:52 UTC, weremexii commented on storage/onedrive.py
> +        # https://docs.microsoft.com/zh-cn/graph/api/driveitem-createuploadsession?view=graph-rest-1.0
按照文档更换了上传方法
这个方法似乎主要服务于分块上传,必须在header里配置`Content-Range`,否则返回400
分块的最大大小为60Mib,应该足够上传图片了,于是`Content-Range`里配置了整个文件的字节范围

这边还有个问题是在create file时,如果有同名文件会返回409
文档里有提到处理方法,我想问一下默认操作设置成覆盖可以吧

2021-02-01 07:26 UTC, y-young commented on storage/onedrive.py
> +        # https://docs.microsoft.com/zh-cn/graph/api/driveitem-createuploadsession?view=graph-rest-1.0
60MB应该足够，Telegram Bot API的文件限制是50MB
默认操作设置为覆盖没问题
分块我再想想，文档里的最佳实践是10MB一个分块，但是这样的话得注意分块大小需为320KB的倍数
> 对大于 10 MiB（10,485,760 个字节）的文件使用可恢复文件传输。
最佳的字节范围大小是 10 MiB，可以实现稳定高速连接。 对于速度较慢或不可靠的连接，较小的文件片段大小可能会给你带来更好的结果。 建议使用的片段大小为 5-10 MiB 之间。
使用 320 KiB（327,680 个字节）倍数的字节范围大小。 如果使用的片段大小不是 320 KiB 的倍数，可能会在上传最后一个字节范围后导致大文件传输失败。

2021-02-01 07:43 UTC, weremexii commented on storage/onedrive.py
> +        # https://docs.microsoft.com/zh-cn/graph/api/driveitem-createuploadsession?view=graph-rest-1.0
那就按320KB来分块吧,网络上的图片从几百KB到几MB不等
我打算试着用一个循环320KB一块一块地上传,可以实现吧,有什么要注意的?

2021-02-01 07:47 UTC, y-young approved these changes

2021-02-01 08:32 UTC, merged

2021-02-01 08:33 UTC, y-young commented
感谢你的贡献！
现在可以麻烦你在Wiki里补充一下使用指南吗？

2021-02-01 08:58 UTC, weremexii commented
非常乐意!

我大概会在wiki里使用一个微软的[sample](https://github.com/Azure-Samples/ms-identity-python-webapp)来让用户获取`refresh_token`

2021-02-01 12:02 UTC, weremexii commented
大致是这样的

https://raw.githubusercontent.com/weremexii/nazurin/master/wiki/OneDrive.md

2021-02-01 12:06 UTC, y-young commented
> 大致是这样的
> 
> https://raw.githubusercontent.com/weremexii/nazurin/master/wiki/OneDrive.md

你可以试试能否直接在Wiki里编辑？Collaborator应该有权限

2021-02-01 12:17 UTC, weremexii commented
> > 大致是这样的
> > https://raw.githubusercontent.com/weremexii/nazurin/master/wiki/OneDrive.md
> 
> 你可以试试能否直接在Wiki里编辑？Collaborator应该有权限

没有找到可以按的按钮🥲

2021-02-01 12:29 UTC, y-young commented
> > > 大致是这样的
> > > https://raw.githubusercontent.com/weremexii/nazurin/master/wiki/OneDrive.md
> > 
> > 
> > 你可以试试能否直接在Wiki里编辑？Collaborator应该有权限
> 
> 没有找到可以按的按钮🥲

原来是我理解错了，contributor不等于collaborator（
没事，我来添加吧
（后面要是有需求的话就考虑换readthedocs.io）

2021-02-01 12:37 UTC, weremexii commented
> > > > 大致是这样的
> > > > https://raw.githubusercontent.com/weremexii/nazurin/master/wiki/OneDrive.md
> > > 
> > > 
> > > 你可以试试能否直接在Wiki里编辑？Collaborator应该有权限
> > 
> > 
> > 没有找到可以按的按钮🥲
> 
> 原来是我理解错了，contributor不等于collaborator（
> 没事，我来添加吧
> （后面要是有需求的话就考虑换readthedocs.io）

幸苦了😁