feat: add support for S3 compatible storage
y-young/nazurin pull request #84
Opened 2023-09-23 13:06 UTC by Kare-Udon

Add a new storage option: S3.
You can use any S3 compatible services.

2023-09-24 08:43 UTC, y-young requested changes

2023-09-24 08:43 UTC, y-young commented on nazurin/storage/s3.py
> +            object_name=file.name,
Concatenate `file.destination` and `file.name` to build the path.

2023-09-24 08:43 UTC, y-young commented on docs/includes/storage.zh.md
> +| [S3](https://aws.amazon.com/s3/)                                                         |         [S3](/storage/s3)             |     `S3`      |             |
`/zh/storage/s3`

2023-09-24 08:43 UTC, y-young commented on nazurin/storage/s3.py
> +# -*- coding: utf-8 -*-
No longer needed.

2023-09-24 08:43 UTC, y-young commented on nazurin/storage/s3.py
> +S3_REGION = env.str("S3_REGION", default="null")
Are you sure it's not `None`?

2023-09-24 08:43 UTC, y-young commented on nazurin/storage/s3.py
> +    async def upload(self, file: File):
Seems the client is not asynchronous, try using `async_wrap`, same for other methods.

2023-09-24 08:43 UTC, y-young commented on nazurin/storage/s3.py
> +S3_ENDPOINT = env.str("S3_ENDPOINT", default="s3.amazonaws.com")
Use `with env.prefixed("S3_"):`

2023-09-25 13:05 UTC, y-young commented on nazurin/storage/s3.py
> +            object_name=f"{file.destination}/{file.name}",
Use `pathlib.Path` and `as_posix()`

2023-09-26 01:08 UTC, Kare-Udon commented on nazurin/storage/s3.py
> +            object_name=f"{file.destination}/{file.name}",
sry, typical error :(

2023-09-26 13:20 UTC, merged